services:
  - type: web
    name: training-backend
    env: docker
    repo: https://github.com/Eazizbek/field_training_bot
    dockerfilePath: Dockerfile.backend
    buildFilter:
      paths:
        - Dockerfile.backend
    plan: free
    envVars:
      - fromGroup: field-training-bot

  - type: worker
    name: training-bot
    env: docker
    repo: https://github.com/Eazizbek/field_training_bot
    dockerfilePath: Dockerfile.bot
    buildFilter:
      paths:
        - Dockerfile.bot
    plan: free
    envVars:
      - fromGroup: field-training-bot

  - name: training-redis
    type: redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all IPs

databases:
  - name: training-db
    plan: free
    postgresMajorVersion: 14
    ipAllowList: []
    databaseName: training_db
    user: training_user
