services:
  - type: web
    name: training-backend
    env: docker
    repo: https://github.com/Eazizbek/field_training_bot
    dockerfilePath: Dockerfile.backend
    buildFilter:
      paths:
        - Dockerfile.backend
    plan: free
    envVars:
      - fromDotEnv: true

  - type: worker
    name: training-bot
    env: docker
    repo: https://github.com/Eazizbek/field_training_bot
    dockerfilePath: Dockerfile.bot
    buildFilter:
      paths:
        - Dockerfile.bot
    plan: free
    envVars:
      - fromDotEnv: true

  - name: training-redis
    type: redis
    plan: free

databases:
  - name: training-db
    plan: free
    postgresMajorVersion: 14
    ipAllowList: []
    databaseName: training_db
    user: training_user
